### ISSUE TITLE
Archive fails at startup on staging.cnx.org for Release 26-Feb-2019

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx#236]
## Overview
Automation tests are failing in the staging.cnx.org environment.

The automation tests discovered the staging environment is broken. Debugging has shown that it's because cnx-archive has an error that brings the site down.

## Debug Info

The archive application log shows the following error:
```pytb
Traceback (most recent call last):
  File "/var/cnx/venvs/archive/bin/pserve", line 10, in <module>
    sys.exit(main())
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 32, in main
    return command.run()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/scripts/pserve.py", line 257, in run
    app = loader.get_wsgi_app(app_name, config_vars)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/plaster_pastedeploy/__init__.py", line 131, in get_wsgi_app
    global_conf=defaults)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 235, in invoke
    filtered = context.next_context.create()
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/__init__.py", line 154, in main
    config.scan(ignore='.tests')
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 881, in scan
    package, categories=categories, onerror=onerror, ignore=ignore
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/cache.py", line 17, in <module>
    from .search import search as database_search
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/search.py", line 19, in <module>
    from .database import SQL_DIRECTORY, db_connect
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/database.py", line 17, in <module>
    from cnxdb.triggers.transforms import (
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxdb/triggers/transforms/__init__.py", line 10, in <module>
    from .resolvers import *  # noqa
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxdb/triggers/transforms/resolvers.py", line 17, in <module>
    from cnxarchive.utils import split_ident_hash, join_ident_hash
  File "/var/cnx/venvs/archive/local/lib/python2.7/site-packages/cnxarchive/utils/__init__.py", line 10, in <module>
    from cnxdb.ident_hash import *  # noqa
ImportError: No module named ident_hash
```

**Comment by pumazi** [comment]
I feel the dependent cnx-db changes probably didn't make it into the release. I'll verify this and make adjustments as needed.

**Comment by m1yag1** [comment]
Automated test failures can be seen in Travis: https://travis-ci.org/openstax/cnx-automation/jobs/495418523

**Comment by pumazi** [comment]
https://github.com/openstax/cnx-deploy/pull/1005 will need to be included in this release. See the changelog entry on the PR.

Basically, this contains the logic archive is complaining it doesn't have.

**Comment by pumazi** [comment]
https://github.com/openstax/cnx-deploy/pull/1014 is merged and should resolve the error.

**Comment by pumazi** [comment]
@scb6 can you retag cnx-deploy with this merged ☝️ change? CC @brittweinstein

**Comment by pumazi** [comment]
Deployed and resolved
