### ISSUE TITLE
CLI - Installation of the CLI tool

### ISSUE THREAD

**Issue by edwoodward** [openstax/cnx#264]
The CLI will be a series of Docker containers that can be easily installed using a docker-compose command. The input and output directories will be outside the containers so developers have easy access to change content and view the output. 

See [Baked PDF Technical Brief](https://docs.google.com/document/d/12OOzczQx-AJKN3C2pDgbs9I1rQ8XmUchcET5k0rCGH4/edit#heading=h.rdrp96p2bs5x)

**Comment by Bkblodget** [comment]
From @omehes (unable to run mathify command):

Run
neb mathify -v "foldername"

Nebuchadnezzar 9.1.0b1

The following error message appears and process stops:

```(cnx-automation) Ottos-MacBook-Pro-633:PDFTEST om9$ neb mathify -v bethics3
Using the configuration file at /Users/om9/.config/nebuchadnezzar.ini
Traceback (most recent call last):
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1229, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1275, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1224, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1016, in _send_output
self.send(msg)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 956, in send
self.connect()
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
sock.connect(self.unix_socket)
FileNotFoundError: [Errno 2] No such file or directory```

During handling of the above exception, another exception occurred:

```Traceback (most recent call last):
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
raise value.with_traceback(tb)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1229, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1275, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1224, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 1016, in _send_output
self.send(msg)
File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/http/client.py", line 956, in send
self.connect()
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/docker/transport/unixconn.py", line 42, in connect
sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))```

During handling of the above exception, another exception occurred:

```Traceback (most recent call last):
File "/Users/om9/.pyenv/versions/cnx-automation/bin/neb", line 11, in 
load_entry_point('nebuchadnezzar==9.1.0b1', 'console_scripts', 'neb')()
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, *ctx.params)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 555, in invoke
return callback(args, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, *kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/_common.py", line 54, in wrapper
return func(args, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/mathify.py", line 56, in mathify
client.images.pull(IMAGE_TAG)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/docker/models/images.py", line 441, in pull
repository, tag=tag, stream=True, **kwargs
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/docker/api/image.py", line 397, in pull
stream=stream, timeout=None
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/docker/utils/decorators.py", line 46, in inner
return f(self, *args, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/docker/api/client.py", line 221, in _post
return self.post(url, **self._set_request_timeout(kwargs))
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
return self.request('POST', url, data=data, json=json, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
(cnx-automation) Ottos-MacBook-Pro-633:PDFTEST om9$```

This is most likely happening because docker needs to be installed

**Comment by omehes** [comment]
Additional info to the above "mathify" issue:
- after installing docker, neb mathify works

Docker needs to be installed in order for the neb mathify to work!
