### ISSUE TITLE
neb assemble fails on Calculus 1, College Algebra, and similar books

### ISSUE THREAD

**Issue by omehes** [openstax/cnx#290]
Use Calculus or Algebra books.
This issue does not happen on US History or Business Ethics books, neb assemble works fine.

Nebuchadnezzar 9.1.0b1 

Steps:
1. neb get -r staging col11759 latest
2. neb assemble col11759_1.10.2 COLALG1
Expected result: assemble should run successfully
Actual result: in the new directory only two files are created, collection.assembled.xhtml and collection.xml. All other module files are missing. A traceback error message appears:

Traceback (most recent call last):
  File "/Users/om9/.pyenv/versions/cnx-automation/bin/neb", line 11, in <module>
    load_entry_point('nebuchadnezzar==9.1.0b1', 'console_scripts', 'neb')()
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/_common.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/assemble.py", line 69, in assemble
    collection_xhtml = produce_collection_xhtml(binder, output_dir)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/assemble.py", line 20, in produce_collection_xhtml
    fb.write(bytes(SingleHTMLFormatter(binder)))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 302, in __bytes__
    self.build()
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 268, in build
    self._build_binder(self.binder, self.body)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 255, in _build_binder
    self._build_binder(node, child_elem)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 257, in _build_binder
    html = bytes(HTMLFormatter(node, generate_ids=True))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 197, in __bytes__
    return _fix_namespaces(html.encode('utf-8'))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 328, in _fix_namespaces
    et = ET.parse(BytesIO(html))
  File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: unbound prefix: line 122, column 11

**Comment by omehes** [comment]
This is a non-cnx book: https://legacy-staging.cnx.org/content/m22453/1.3/?collection=col10621/1.22&legacy=true

neb assemble fails

```
(cnx-automation) Ottos-MacBook-Pro-635:PDFTEST om9$ neb assemble col10621_1.22.2 PROGRC1
Traceback (most recent call last):
  File "/Users/om9/.pyenv/versions/cnx-automation/bin/neb", line 11, in <module>
    load_entry_point('nebuchadnezzar==9.1.0b1', 'console_scripts', 'neb')()
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/_common.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/assemble.py", line 69, in assemble
    collection_xhtml = produce_collection_xhtml(binder, output_dir)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/nebu/cli/assemble.py", line 20, in produce_collection_xhtml
    fb.write(bytes(SingleHTMLFormatter(binder)))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 302, in __bytes__
    self.build()
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 268, in build
    self._build_binder(self.binder, self.body)
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 243, in _build_binder
    html = bytes(HTMLFormatter(node, generate_ids=False))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 197, in __bytes__
    return _fix_namespaces(html.encode('utf-8'))
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/formatters.py", line 328, in _fix_namespaces
    et = ET.parse(BytesIO(html))
  File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/xml/etree/ElementTree.py", line 1197, in parse
    tree.parse(source, parser)
  File "/Users/om9/.pyenv/versions/3.7.0/lib/python3.7/xml/etree/ElementTree.py", line 598, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 20, column 32
```

**Comment by pumazi** [comment]
It's failing on `m51252`. The specific content snippet is:
```xml
<para id="fs-id1787344">Each point in the plane is identified by its <term><emphasis effect="italics">x-</emphasis>coordinate</term>, or horizontal displacement from the origin, and its <term><emphasis effect="italics">y-</emphasis>coordinate</term>, or vertical displacement from the origin. Together, we write them as an <term>ordered pair</term> indicating the combined distance from the origin in the form<m:math>
 <m:mrow>
  <m:mtext> </m:mtext><m:mrow><m:mo>(</m:mo>
   <m:mrow>
    <m:mi>x</m:mi><m:mo>,</m:mo><m:mi>y</m:mi>
   </m:mrow>
  <m:mo>)</m:mo></m:mrow><m:mo>.</m:mo><m:mtext> </m:mtext>
 </m:mrow>

</m:math>
An ordered pair is also known as a coordinate pair because it consists of
<emphasis effect="italics">x-</emphasis>
and
<emphasis effect="italics">y</emphasis>
-coordinates. For example, we can represent the point
<m:math>
 <m:mrow>
   <m:mtext> </m:mtext>
   <m:mo stretchy="false">(</m:mo><m:mn>3</m:mn><m:mo>,</m:mo><m:mn>−1</m:mn><m:mo stretchy="false">)</m:mo>
   <m:mtext> </m:mtext>
 </m:mrow>
</m:math>
in the plane by moving three units to the right of the origin in the horizontal direction, and one unit down in the vertical direction. See <link target-id="Figure_02_01_004"/>.</para>```

**Comment by pumazi** [comment]
I've been able to determine the error is due to math in the abstract or summary. I'd guess we aren't doing the same "namespace fixing" as we do with the content. We end up with `<m:math> ...</m:math>` in the body of our content.

I've repeatedly been able to progress forward in the process by removing the math elements from the summary text. So far `m51252`, `m51255` and `m51266` have displayed this common trait. 

Note the error message coming out of our logic doesn't point anywhere close to where this is actually located in the content. So that's a red herring, if I ever saw one.
