### ISSUE TITLE
cnx-epub-validate-collated throws an error

### ISSUE THREAD

**Issue by omehes** [openstax/cnx#293]
steps:
1. neb get -r staging col11992 latest
2. neb assemble col11992_1.21.1 ASTRON
3. cnx-epub-validate-collated ASTRON/collection.assembled.xhtml
Expected result: validation is successful
Actual result: ModuleNotFoundError: 
Traceback (most recent call last):
  File "/Users/om9/.pyenv/versions/cnx-automation/bin/cnx-epub-validate-collated", line 10, in <module>
    sys.exit(main())
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/scripts/collated_single_html/main.py", line 48, in main
    from cnxepub.collation import reconstitute
  File "/Users/om9/.pyenv/versions/3.7.0/envs/cnx-automation/lib/python3.7/site-packages/cnxepub/collation.py", line 14, in <module>
    from cnxeasybake import Oven
ModuleNotFoundError: No module named 'cnxeasybake'

This happens with any collection I try.

Nebuchadnezzar 9.1.0b1

**Comment by pumazi** [comment]
The fix for this is to do `pip install --upgrade "cnx-epub[collation]"`. The part in the brackets is to include the extra optional requirements for cnx-epub. Right now nebuchadnezzar does not need cnx-epub with collation (aka baking) support. It's a small hassle to install this bit on the Mac (due to something call pyicu).

---

Great report! I'm going to chalk this up under "won't fix" for Nebuchadnezzar, because baking is currently outside the the scope of the application. However, **a better error should show up for this script. At least it could suggest you are missing an optional dependency**. So at the very least, let's fix that.
